### ISSUE TITLE
inject angular logic optionally

### ISSUE THREAD

**Issue by akostadinov** [titusfortner/watir_angular#1]
Hi, 

I see that gem is monkey patching the angular logic into Watir 

https://github.com/titusfortner/watir_angular/blob/master/lib/extensions/watir/browser.rb

Maybe it is just me and probably not an issue for most projects but I prefer to include add-ons explicitly. For example:
```
WatirAngular.inject(browser)
```

It could still monkey patch the browser **object** but not the whole class.

In any case, thanks a lot for spending time on this extension! I'll be trying it out as soon as I can.

**Comment by titusfortner** [comment]
Well, the additional locators I'm ok with being foisted when requiring the gem, but you make a good point that the auto-waiting might be too much.

I kind of think the waiting method should be added to `Browser` to allow user to do: `browser.wait_for_angular`. But perhaps the auto-waiting should be toggled explicitly by `WatirAngular.auto_wait(browser)`? Unless the names should be different. I'm not sure `#inject` gives enough context for what it does. Something like:

```ruby
def self.auto_wait(browser) do
  proc = ->(browser) { browser.wait_for_angular }
  browser.after_hooks.add(proc)
end
```

**Comment by akostadinov** [comment]
With `inject` I was thinking more about some standard way to include some extension to Watir browser object. Maybe another word could fit better.

i.e. saying: "WatirAngular, modify my browser object with angular selectors, wait methods and whatever you implement as well!"

If one wants to use multiple extensions, one can inject selected extensions to selected browsers. I don't know how common would such use case be. Just a suggestion that it keeps the main class clean.

For example, I'm testing OpenShift. Most web related tests are against management console that's based on angular. But sometimes a browser is spawned to test random web applications run on top of the platform. I don't think existing WatirAngular would break this use case. Just if more of these extensions are written, chances for conflicts may increase.

What you suggest is a middle ground - selectors always included and auto-waiting optionally. Chances for side effects would be lower.

**Comment by titusfortner** [comment]
Any interest in making a PR for it?
I don't actually use angular right now, I just wanted to get something out there for people to adjust as necessary.

Wrong locators? Too many? things in protractor we can steal? Etc.

**Comment by akostadinov** [comment]
a little bit sick this week, but I'll take a look when I get back on track

**Comment by titusfortner** [comment]
Check out 0.3.0 and see if it does everything you need.

**Comment by akostadinov** [comment]
What I see is really nice. There is a small issue in docs - should read `inject_wait` instead of `inject_angular_wait`.

Also I see that the additional selectors are now gone but I don't see it as a major issue.

I didn't yet test it, but I will definitely do in the next couple of days.

**Comment by titusfortner** [comment]
Ah, good catch on the docs.

Custom selectors are still there, along with custom methods as well which I didn't implement before. It just doesn't need to use the locator code from Watir, it just needs [these two lines](https://github.com/titusfortner/watir_angular/blob/master/lib/watir_angular.rb#L6-L7)
